"""Izinlere aciklama eklendi

Revision ID: acb9c70a9e82
Revises: 0f2cde456db1
Create Date: 2025-08-07 07:27:08.442931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acb9c70a9e82'
down_revision = '0f2cde456db1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
