"""Add minimum_stock_level to Product model

Revision ID: 9aa6b38d9afd
Revises: c73cb84c93e1
Create Date: 2025-08-09 11:26:44.108142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9aa6b38d9afd'
down_revision = 'c73cb84c93e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('minimum_stock_level', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('minimum_stock_level')

    # ### end Alembic commands ###
