"""Add product and location analysis tables

Revision ID: f504e7f3f207
Revises: 9aa6b38d9afd
Create Date: 2025-08-09 15:48:54.950388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f504e7f3f207'
down_revision = '9aa6b38d9afd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('analysis_date', sa.DateTime(), nullable=False),
    sa.Column('daily_velocity', sa.Float(), nullable=True),
    sa.Column('days_of_supply', sa.Integer(), nullable=True),
    sa.Column('last_movement_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_analysis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_analysis_product_id'), ['product_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_product_analysis_status'), ['status'], unique=False)

    op.create_table('location_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('analysis_date', sa.DateTime(), nullable=False),
    sa.Column('total_movements', sa.Integer(), nullable=True),
    sa.Column('pick_count', sa.Integer(), nullable=True),
    sa.Column('place_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('location_analysis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_location_analysis_location_id'), ['location_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_location_analysis_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location_analysis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_location_analysis_status'))
        batch_op.drop_index(batch_op.f('ix_location_analysis_location_id'))

    op.drop_table('location_analysis')
    with op.batch_alter_table('product_analysis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_analysis_status'))
        batch_op.drop_index(batch_op.f('ix_product_analysis_product_id'))

    op.drop_table('product_analysis')
    # ### end Alembic commands ###
